---
title: "Insects_data"
author: "Mihkail Cornell"
date: "2023-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidymodels)
library(tidyr)
library(tidyverse)
library(stringr)
library(dplyr)
library(lubridate)
library(tidyselect)

insect_raw <- read_csv("analysis_insect_pests/pest.csv")
```

```{r}
# corn plant hopper damage rating
hopper_df <- 
  insect_raw %>%
  select(FarmID, `Collection Date`, Province, Municipality, `Crop Stage`, Treatment, `Corn Type`, Variety, 
         contains("Corn Plant Hopper - Damage Rating")) %>%
  filter(Municipality == "Alangalang")

# convert date format
hopper_df$collect_date <- 
  as.Date(hopper_df$`Collection Date`, "%B %d, %Y")

hopper_dmg <-
  hopper_df %>% 
  mutate(Year = year(collect_date), Month = month(collect_date))
  # rowwise() %>%
  # mutate(hopper_median_damage = median(c(`Corn Plant Hopper - Damage Rating 1`:`Corn Plant Hopper - Damage Rating 20`))) 
```


```{r}
# merged with monthly average weather parameters
classification_dmg <- function(x) {ordered(x, levels = c("No", "Light", "Moderate", "Severe", "High"))}

getmode <- function(v) {
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

hopper_joined <-
  hopper_dmg %>% 
  left_join(collection_weather_avg, by=c('Year', 'Month')) %>%
  # mutate_at(c(9:28), as.factor) %>%
  mutate(across(contains("Corn Plant Hopper - Damage Rating "), 
         ~ case_when( . == 1 ~ "No",
                      . == 3 ~ "Light",
                      . == 5 ~ "Moderate",
                      . == 7 ~ "Severe",
                      . == 9 ~ "High"), 
         .names="Class_Infest_{.col}")) %>%
  mutate(across(contains("Class_Infest_Corn Plant Hopper - Damage Rating "), ~classification_dmg(.))) %>%
   mutate(Mode_class_infest_hopper = getmode(c_across(contains("Class_Infest_Corn Plant Hopper - Damage Rating "))))
         
```


```{r}
hopper_parsed <- 
  hopper_joined %>% 
  select(Municipality, collect_date, `Crop Stage`, Treatment, `Corn Type`, Variety, hopper_median_damage, mean_temp:median_humid) %>%
  mutate(variety = case_when(str_detect(Variety, 'OPV') ~ "OPV White",
                             str_detect(Variety, "\\b[MmAaCcHhOo]") ~ "Macho F1",
                             str_detect(Variety, "^J") ~ "J505",
                             TRUE ~ Variety)) %>% select(-Variety)

hopper_parsed$variety %>% unique()
hopper_parsed$`Corn Type` %>% unique()
```

```{r}
hopper_parsed %>%
  ggplot(aes(mean_temp, hopper_median_damage)) +
  geom_point() +
  theme_minimal()

hopper_parsed %>% names()
```
```{r}
library(corrr)



hopper_parsed %>%
  correlate()
```

```{r}
```















